# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-428d823d-73ee-4499-a460-0727a9dc0207";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-428d823d-73ee-4499-a460-0727a9dc0207".device = "/dev/disk/by-uuid/428d823d-73ee-4499-a460-0727a9dc0207";
  boot.initrd.luks.devices."luks-079c0b46-cfb3-4ebc-9dcb-d54f0e27a75b".device = "/dev/disk/by-uuid/079c0b46-cfb3-4ebc-9dcb-d54f0e27a75b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5908-AA9C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-079c0b46-cfb3-4ebc-9dcb-d54f0e27a75b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
